### PR TITLE
Add feature/contactUs page

### PR DESCRIPTION
**Pull request by eshaalal**
Completed the ContactUs Page

Task 1 : Added the "ContactUs " icon in navbar

Screenshot 2024-10-08 174215

Task 2 : Created the Whole contact Us page 

https://github.com/user-attachments/assets/75267f05-29e6-46b5-aaeb-622fffd0c904

### CODE REVIEW

**Comment by eshaalal** [comment]
@Yashgabani845 I have created the contact Page please check it! and let me know if anything else is needed
I would really be thankful if you consider it merging with level-3

**Comment by eshaalal** [comment]
More cleaner video of contact page 


https://github.com/user-attachments/assets/875034c5-263f-4c24-a57b-018107a4998c

**Comment by eshaalal** [comment]
@Yashgabani845 I have resolved the conflicts as well, looking forward for your response

**Comment by Yashgabani845** [comment]
@eshaalal checkout current contact us page and integrat your page in that page and then make PR by resolving merger conflicts 
you have good fucntionalities

**Comment by Yashgabani845** [comment]
@eshaalal also add node modules in gitignoe file and remove the node moules in PR

**Pull request closed without merging**
