### PR TITLE
added loader and toast notification

### PR DESCRIPTION
**Pull request by AyushSharma72**
added loader and toast notification when contact form is subimtted  #237
 
loader:
Screenshot (19)

toast:
Screenshot (20)

@Yashgabani845 
please review this pr @Yashgabani845

### CODE REVIEW

**Comment by AyushSharma72** [comment]
> added loader and toast notification when contact form is subimtted #237
> 
> loader: Screenshot (19)
> 
> toast: Screenshot (20)
> 
> @Yashgabani845 please review this pr @Yashgabani845

can you please review this pr @Yashgabani845

**Comment by Yashgabani845** [comment]
@AyushSharma72 remove unwanted packages files

**Comment by AyushSharma72** [comment]
> @AyushSharma72 remove unwanted packages files

there are only package.json and package.lock.json files @Yashgabani845

**Comment by Yashgabani845** [comment]
@AyushSharma72 add package-lock.json in gitignore then make commit

**Comment by AyushSharma72** [comment]
> @AyushSharma72 add package-lock.json in gitignore then make commit

right now i deleted the file next time i will add it to gitignore @Yashgabani845

**Pull request closed without merging**
