### PR TITLE
fixed filters and job post issue

### PR DESCRIPTION
**Pull request by Garvit1000**
### Pull Request Title

**Issue Reference:**
#97  and #114 

**Description:**
fixed  post job api error and   added  working filters  in jobs page 

**Screenshots:**
Screenshot from 2024-10-10 21-56-02
Screenshot from 2024-10-10 19-52-23
Screenshot from 2024-10-10 19-52-32

**Type of change:**
- [x] Bug fix

**Checklist:**
- [x] I have tested my changes and verified that they work
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Garvit1000** [comment]
@Yashgabani845  please look this

**Comment by Yashgabani845** [comment]
@Garvit1000 resolve merger conflicts

**Comment by Garvit1000** [comment]
@Yashgabani845 done

**Comment by Yashgabani845** [comment]
@Garvit1000 reoslve the merge conflcts

**Comment by Garvit1000** [comment]
@Yashgabani845  i  think it should work now

**Comment by Garvit1000** [comment]
@Yashgabani845 done

**Review by Yashgabani845 — APPROVED** [review]

**Pull request merged**
