### PR TITLE
Implement Dark Theme Feature ✨

### PR DESCRIPTION
**Pull request by AnushkaChouhan25**
### Pull Request Title

**Issue Reference:**
#259 
**Description:**
I added a dark theme feature to the HireHub project. This provides users with an alternative viewing option, improving accessibility and user experience, especially in low-light environments.

**Screenshots:**
image
image
image
image
image

**Type of change:**
- [x] Bug fix
- [x] New feature
- [ ] Breaking change
- [x] Enhancement

**Checklist:**
- [x] I have tested my changes and verified that they work
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas 
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

**Additional Information:**

### CODE REVIEW

**Comment by Yashgabani845** [comment]
@AnushkaChouhan25 it is not looking good make proper black theme

**Comment by AnushkaChouhan25** [comment]
@Yashgabani845 Is it fine ?
image

**Comment by AnushkaChouhan25** [comment]
or this one 
image

**Comment by AnushkaChouhan25** [comment]
or this one 
image

**Comment by AnushkaChouhan25** [comment]
@Yashgabani845 can you please review it

**Comment by AnushkaChouhan25** [comment]
@Yashgabani845 Can you please respond?

**Pull request merged**
