### PR TITLE
Add authentication to routes

### LINKED ISSUE #247: [Bug] Authentication for routes.
**Describe the bug**

there should be authentication checks for the routes "scan resume" and "create blog". 
users should not be allowed these services if they are not logged in to the platform.

**To Reproduce**
1. Go to scan resume/ crate blog
2. Visitors are allowed to use these.

**Expected behavior**
Visitors must be allowed only after successful login

**Screenshots**
Screenshot 2024-10-27 001942

### PR DESCRIPTION
**Pull request by haseebzaki-07**
### Pull Request Title

**Issue Reference:**
## fixes #247 

**Description:**
This PR adds the authMiddleware to the blog routes so that unauthenticated users are not allowed.

**Screenshots:**
Screenshot 2024-10-28 213517
Screenshot 2024-10-28 213809
Screenshot 2024-10-28 213825

**Type of change:**
- [ ] Bug fix
- [X] New feature
- [ ] Breaking change
- [ ] Enhancement

**Checklist:**
- [X] I have tested my changes and verified that they work
- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by haseebzaki-07** [comment]
@Yashgabani845 please review this PR

**Comment by haseebzaki-07** [comment]
@Yashgabani845 please add the levels and please let me know if there are more issues that I can work on!

**Comment by haseebzaki-07** [comment]
@Yashgabani845 please add the labels

**Comment by haseebzaki-07** [comment]
hey @Yashgabani845 please add the labels here

**Comment by haseebzaki-07** [comment]
@Yashgabani845 !!

**Comment by Yashgabani845** [comment]
@haseebzaki-07 done

**Comment by haseebzaki-07** [comment]
@Yashgabani845 Thank you!

**Pull request merged**
