### PR TITLE
Feature/spinners loader

### PR DESCRIPTION
**Pull request by itsmeAYUSH**
### Pull Request Title

**Issue Reference:**
Added spinners and loading screen on various components/pages where ever necessary.

**Description:**
This PR implements a loading spinner on the Employer page to enhance user experience while the images are loading. The loader color has been changed to a visually appealing shade of blue (#4e9ff5). This change improves feedback for users during image load times, ensuring they are aware that the content is being processed.

**Screenshots:**
image

**Type of change:**
- [ ] Bug fix
- [✓] New feature
- [ ] Breaking change
- [ ] Enhancement

**Checklist:**
- [✓] I have tested my changes and verified that they work
- [✓] My code follows the style guidelines of this project
- [✓] I have commented my code, particularly in hard-to-understand areas
- [✓] I have made corresponding changes to the documentation
- [✓] My changes generate no new warnings
- [✓] I have added tests that prove my fix is effective or that my feature works
- [✓] New and existing unit tests pass locally with my changes

**Additional Information:**

### CODE REVIEW

**Comment by Yashgabani845** [comment]
@AyushSharma72  you are pushing node modules please remvove them via adding ndoe mpodule in gitignore

**Comment by AyushSharma72** [comment]
> @AyushSharma72 you are pushing node modules please remvove them via adding ndoe mpodule in gitignore

this pr is not mine @Yashgabani845   
@itsmeAYUSH  made the pr

**Comment by itsmeAYUSH** [comment]
hey @Yashgabani845 Please check my request again and let me know if any further updates are needed.
Thank you.

**Comment by Yashgabani845** [comment]
@itsmeAYUSH  resolve the conflicts

**Comment by itsmeAYUSH** [comment]
hey @Yashgabani845 Please check my request again and let me know if any further updates are needed.
Thank you.

**Comment by Yashgabani845** [comment]
@itsmeAYUSH resolve the merge conflicts

**Pull request closed without merging**
