### PR TITLE
Added privacy policy page

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue #105 

Screenshot 2024-10-12 022221

Screenshot 2024-10-12 022234

builded a good looking website theme oriented privacy policy page

### CODE REVIEW

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah chnage the font and font colour do not use blue a everything and times new roman 
make it more good

**Comment by Sawan-Kushwah** [comment]
image

@Yashgabani845 is it good or i try some more color combination

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah color is good change the font  don't use times new Roman 
And also resolve merge conflict

**Comment by Sawan-Kushwah** [comment]
@Yashgabani845 done

**Pull request merged**
