### PR TITLE
Updated Readme file

### PR DESCRIPTION
**Pull request by Aditi-008**
Issue #53 Resolved. Kindly merge and in case you wish to add more information kindly let me know.
Thank you

### CODE REVIEW

**Comment by Aditi-008** [comment]
Dear sir 
Kindly merge it.

**Comment by Aditi-008** [comment]
If possible sir pls label as hacktoberfest too..

**Comment by Yashgabani845** [comment]
@Aditi-008  sorry this project is not part of hacktoberfest

**Comment by Aditi-008** [comment]
Ok sir 
Thank you

**Pull request merged**
